# Hugo build configuration for Netlify
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)
# Default build settings
[build]
  publish = "public"
  command = "cd themes/docsy && git submodule update -f --init && cd ../.. && hugo"

# "production" environment specific build settings
[build.environment]
  HUGO_VERSION = "0.71.1"
  HUGO_THEME = "docsy"
  HUGO_ENV = "production"

# section redirects
[[redirects]]
  from = "/halyard-release-notes"
  to = "/docs/release-notes/rn-armory-halyard"
  status = 301
  force = false

[[redirects]]
  from = "/release-notes"
  to = "/docs/release-notes/rn-armory-spinnaker"
  status = 301
  force = false

[[redirects]]
  from = "/spinnaker"
  to = "/docs/spinnaker"
  status = 301
  force = false

[[redirects]]
  from = "/operator_reference"
  to = "/docs/operator_reference"
  status = 301
  force = false

[[redirects]]
  from = "/spinnaker-user-guides"
  to = "/docs/spinnaker-user-guides"
  status = 301
  force = false

[[redirects]]
  from = "/spinnaker-install-admin-guides"
  to = "/docs/spinnaker-install-admin-guides"
  status = 301
  force = false
